---
# vars file for cassandra
CASSANDRA_VERSION: 311x # Available options 21x, 22x, 30x, 311x
CASSANDRA_CLUSTER_NAME: eplus
CASSANDRA_CLUSTER_SUBNET: 10.32.68.0/24
CASSANDRA_CLUSTER_SEEDS:
  - 10.32.68.40
  - 10.32.68.41
  - 10.32.68.42
CASSANDRA_STORAGE_PORT: 7000
LISTEN_INTERFACE: ens160
NATIVE_TRANSPORT_PORT: 9042
CASSANDRA_SSL_STORAGE_PORT: 7001

# location of directories
DATA_FILE_DIRECTORIES: /var/lib/cassandra/data
COMMITLOG_DIRECTORY: /var/lib/cassandra/commitlog
SAVED_CACHES_DIRECTORY:
HINTS_DIRECTORY:

# JVM options
JVM_OPTS:

# Logging
LOG_LEVEL: INFO

# Prerequisite packages and versions.
JAVA: 1.8 # Java8
PYTHON_VERSION: 2.7.14
