# This playbook is to identify the list of files under given path,
# using Ansible find module, and delete all the files and directories
# under that path using Ansible file module.
---
- hosts: all
  gather_facts: no
  tasks:
    - name: Get list of files
      find:
        paths: "{{ item }}"
        recurse: yes
        file_type: any
      with_items:
        - /tmp/gopis
      register: files

    - name: Print file names
      debug: var={{ item }}
      with_items: files

    - name: Decompose
      file: path={{ item }} state=absent
      with_items:
        - "{{ files.results[0].files | map(attribute='path') | list }}"
